/**
 * AlgorithmHub
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.algorithmhub) {
      root.algorithmhub = {};
    }
    root.algorithmhub.InlineResponse2007 = factory(root.algorithmhub.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InlineResponse2007 model module.
   * @module model/InlineResponse2007
   * @version 0.2.5
   */

  /**
   * Constructs a new <code>InlineResponse2007</code>.
   * @alias module:model/InlineResponse2007
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse2007</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2007} obj Optional instance to populate.
   * @return {module:model/InlineResponse2007} The populated <code>InlineResponse2007</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fdrtab')) {
        obj['fdrtab'] = ApiClient.convertToType(data['fdrtab'], Object);
      }
      if (data.hasOwnProperty('OptimalPlot')) {
        obj['OptimalPlot'] = ApiClient.convertToType(data['OptimalPlot'], 'String');
      }
      if (data.hasOwnProperty('_rid')) {
        obj['_rid'] = ApiClient.convertToType(data['_rid'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Object} fdrtab
   */
  exports.prototype['fdrtab'] = undefined;
  /**
   * @member {String} OptimalPlot
   */
  exports.prototype['OptimalPlot'] = undefined;
  /**
   * @member {String} _rid
   */
  exports.prototype['_rid'] = undefined;



  return exports;
}));


