/**
 * AlgorithmHub
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2002', 'model/InlineResponseDefault'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2002'), require('../model/InlineResponseDefault'));
  } else {
    // Browser globals (root is window)
    if (!root.algorithmhub) {
      root.algorithmhub = {};
    }
    root.algorithmhub.RunApi = factory(root.algorithmhub.ApiClient, root.algorithmhub.InlineResponse2002, root.algorithmhub.InlineResponseDefault);
  }
}(this, function(ApiClient, InlineResponse2002, InlineResponseDefault) {
  'use strict';

  /**
   * Run service.
   * @module api/RunApi
   * @version 0.3.0
   */

  /**
   * Constructs a new RunApi. 
   * @alias module:api/RunApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addFileRun operation.
     * @callback module:api/RunApi~addFileRunCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PRIVATE
     * Add a file to the run results
     * @param {String} rid The run id
     * @param {module:api/RunApi~addFileRunCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.addFileRun = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling addFileRun");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/run/{rid}/file', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the detailRun operation.
     * @callback module:api/RunApi~detailRunCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get info about run
     * Get info about the run
     * @param {String} rid The run id
     * @param {module:api/RunApi~detailRunCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2002}
     */
    this.detailRun = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling detailRun");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/run/{rid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getInput operation.
     * @callback module:api/RunApi~getInputCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Input parameters
     * Input parameters
     * @param {String} rid The run id
     * @param {module:api/RunApi~getInputCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    this.getInput = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling getInput");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = Object;

      return this.apiClient.callApi(
        '/run/{rid}/input', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOutput operation.
     * @callback module:api/RunApi~getOutputCallback
     * @param {String} error Error message, if any.
     * @param {Object} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get the output
     * Get the output
     * @param {String} rid The run id
     * @param {module:api/RunApi~getOutputCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object}
     */
    this.getOutput = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling getOutput");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = Object;

      return this.apiClient.callApi(
        '/run/{rid}/output', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOutputFigure operation.
     * @callback module:api/RunApi~getOutputFigureCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get figure as app
     * Get figure as app
     * @param {String} rid The run id
     * @param {String} fid The file id
     * @param {module:api/RunApi~getOutputFigureCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    this.getOutputFigure = function(rid, fid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling getOutputFigure");
      }

      // verify the required parameter 'fid' is set
      if (fid === undefined || fid === null) {
        throw new Error("Missing the required parameter 'fid' when calling getOutputFigure");
      }


      var pathParams = {
        'rid': rid,
        'fid': fid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = File;

      return this.apiClient.callApi(
        '/run/{rid}/figure/{fid}/*', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getOutputFile operation.
     * @callback module:api/RunApi~getOutputFileCallback
     * @param {String} error Error message, if any.
     * @param {File} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a file
     * Get a file
     * @param {String} rid The run id
     * @param {String} filename The filename
     * @param {module:api/RunApi~getOutputFileCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link File}
     */
    this.getOutputFile = function(rid, filename, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling getOutputFile");
      }

      // verify the required parameter 'filename' is set
      if (filename === undefined || filename === null) {
        throw new Error("Missing the required parameter 'filename' when calling getOutputFile");
      }


      var pathParams = {
        'rid': rid,
        'filename': filename
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = File;

      return this.apiClient.callApi(
        '/run/{rid}/file/{filename}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getStatus operation.
     * @callback module:api/RunApi~getStatusCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get status of the run
     * Get status of the run
     * @param {String} rid The run id
     * @param {module:api/RunApi~getStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.getStatus = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling getStatus");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/run/{rid}/status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listOutputFigures operation.
     * @callback module:api/RunApi~listOutputFiguresCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list of figures
     * Get list of figures
     * @param {String} rid The run id
     * @param {module:api/RunApi~listOutputFiguresCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.listOutputFigures = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling listOutputFigures");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/run/{rid}/figures', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listOutputFiles operation.
     * @callback module:api/RunApi~listOutputFilesCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list of output files
     * Get list of output files
     * @param {String} rid The run id
     * @param {module:api/RunApi~listOutputFilesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.listOutputFiles = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling listOutputFiles");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/run/{rid}/files', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the listRuns operation.
     * @callback module:api/RunApi~listRunsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<Object>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get list of runs
     * Get list of runs
     * @param {module:api/RunApi~listRunsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<Object>}
     */
    this.listRuns = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = [Object];

      return this.apiClient.callApi(
        '/run', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postError operation.
     * @callback module:api/RunApi~postErrorCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PRIVATE
     * Post that an error occured and close the run.
     * @param {String} rid The workspace base type.
     * @param {module:api/RunApi~postErrorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.postError = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling postError");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/run/{rid}/error', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postFigure operation.
     * @callback module:api/RunApi~postFigureCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PRIVATE
     * Add a figure from the run
     * @param {String} rid The workspace base type.
     * @param {module:api/RunApi~postFigureCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.postFigure = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling postFigure");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/run/{rid}/figure', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postStatus operation.
     * @callback module:api/RunApi~postStatusCallback
     * @param {String} error Error message, if any.
     * @param {'String'} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PRIVATE
     * Post the status of run
     * @param {String} rid The run id
     * @param {module:api/RunApi~postStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link 'String'}
     */
    this.postStatus = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling postStatus");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/run/{rid}/status', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the setSuccess operation.
     * @callback module:api/RunApi~setSuccessCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * PRIVATE
     * Send output.json and close the run as successful
     * @param {String} rid The run id
     * @param {module:api/RunApi~setSuccessCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.setSuccess = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling setSuccess");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = null;

      return this.apiClient.callApi(
        '/run/{rid}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
