/**
 * AlgorithmHub
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2007', 'model/InlineResponseDefault'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2007'), require('../model/InlineResponseDefault'));
  } else {
    // Browser globals (root is window)
    if (!root.algorithmhub) {
      root.algorithmhub = {};
    }
    root.algorithmhub.UnitTestsApi = factory(root.algorithmhub.ApiClient, root.algorithmhub.InlineResponse2007, root.algorithmhub.InlineResponseDefault);
  }
}(this, function(ApiClient, InlineResponse2007, InlineResponseDefault) {
  'use strict';

  /**
   * UnitTests service.
   * @module api/UnitTestsApi
   * @version 0.2.0
   */

  /**
   * Constructs a new UnitTestsApi. 
   * @alias module:api/UnitTestsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the runKeyboardInterrupt operation.
     * @callback module:api/UnitTestsApi~runKeyboardInterruptCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2007} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check for keyboard interrupt
     * Check for keyboard interrupt during run
     * @param {String} rid The run id
     * @param {module:api/UnitTestsApi~runKeyboardInterruptCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2007}
     */
    this.runKeyboardInterrupt = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling runKeyboardInterrupt");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/run/{rid}/test/keyboardInterrupt', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the runRuntimeError operation.
     * @callback module:api/UnitTestsApi~runRuntimeErrorCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2007} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Check for keyboard interrupt
     * Check for keyboard interrupt during run
     * @param {String} rid The run id
     * @param {module:api/UnitTestsApi~runRuntimeErrorCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2007}
     */
    this.runRuntimeError = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling runRuntimeError");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/run/{rid}/test/runtimeError', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the validatModel operation.
     * @callback module:api/UnitTestsApi~validatModelCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2007} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Runs the unit test cases
     * Runs the unit test cases specified for Model
     * @param {String} mid The model id
     * @param {module:api/UnitTestsApi~validatModelCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2007}
     */
    this.validatModel = function(mid, callback) {
      var postBody = null;

      // verify the required parameter 'mid' is set
      if (mid === undefined || mid === null) {
        throw new Error("Missing the required parameter 'mid' when calling validatModel");
      }


      var pathParams = {
        'mid': mid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/model/{mid}/test/validate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the validateData operation.
     * @callback module:api/UnitTestsApi~validateDataCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2007} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Checks valid data set
     * Checking for valid data set
     * @param {String} did The dataset id
     * @param {module:api/UnitTestsApi~validateDataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2007}
     */
    this.validateData = function(did, callback) {
      var postBody = null;

      // verify the required parameter 'did' is set
      if (did === undefined || did === null) {
        throw new Error("Missing the required parameter 'did' when calling validateData");
      }


      var pathParams = {
        'did': did
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/data/{did}/test/validate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the validateRun operation.
     * @callback module:api/UnitTestsApi~validateRunCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2007} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Runs the unit test cases
     * Runs the unit test cases specified for Run
     * @param {String} rid The run id
     * @param {module:api/UnitTestsApi~validateRunCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2007}
     */
    this.validateRun = function(rid, callback) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling validateRun");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/run/{rid}/test/validate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
