/**
 * AlgorithmHub
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse2007', 'model/InlineResponseDefault'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineResponse2007'), require('../model/InlineResponseDefault'));
  } else {
    // Browser globals (root is window)
    if (!root.algorithmhub) {
      root.algorithmhub = {};
    }
    root.algorithmhub.UnitTestsApi = factory(root.algorithmhub.ApiClient, root.algorithmhub.InlineResponse2007, root.algorithmhub.InlineResponseDefault);
  }
}(this, function(ApiClient, InlineResponse2007, InlineResponseDefault) {
  'use strict';

  /**
   * UnitTests service.
   * @module api/UnitTestsApi
   * @version 0.2.3
   */

  /**
   * Constructs a new UnitTestsApi. 
   * @alias module:api/UnitTestsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Check for keyboard interrupt
     * Check for keyboard interrupt during run
     * @param {String} rid The run id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2007} and HTTP response
     */
    this.runKeyboardInterruptWithHttpInfo = function(rid) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling runKeyboardInterrupt");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/run/{rid}/test/keyboardInterrupt', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Check for keyboard interrupt
     * Check for keyboard interrupt during run
     * @param {String} rid The run id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2007}
     */
    this.runKeyboardInterrupt = function(rid) {
      return this.runKeyboardInterruptWithHttpInfo(rid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Check for keyboard interrupt
     * Check for keyboard interrupt during run
     * @param {String} rid The run id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2007} and HTTP response
     */
    this.runRuntimeErrorWithHttpInfo = function(rid) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling runRuntimeError");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/run/{rid}/test/runtimeError', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Check for keyboard interrupt
     * Check for keyboard interrupt during run
     * @param {String} rid The run id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2007}
     */
    this.runRuntimeError = function(rid) {
      return this.runRuntimeErrorWithHttpInfo(rid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Runs the unit test cases
     * Runs the unit test cases specified for Model
     * @param {String} mid The model id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2007} and HTTP response
     */
    this.validatModelWithHttpInfo = function(mid) {
      var postBody = null;

      // verify the required parameter 'mid' is set
      if (mid === undefined || mid === null) {
        throw new Error("Missing the required parameter 'mid' when calling validatModel");
      }


      var pathParams = {
        'mid': mid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/model/{mid}/test/validate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Runs the unit test cases
     * Runs the unit test cases specified for Model
     * @param {String} mid The model id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2007}
     */
    this.validatModel = function(mid) {
      return this.validatModelWithHttpInfo(mid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Checks valid data set
     * Checking for valid data set
     * @param {String} did The dataset id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2007} and HTTP response
     */
    this.validateDataWithHttpInfo = function(did) {
      var postBody = null;

      // verify the required parameter 'did' is set
      if (did === undefined || did === null) {
        throw new Error("Missing the required parameter 'did' when calling validateData");
      }


      var pathParams = {
        'did': did
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/data/{did}/test/validate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Checks valid data set
     * Checking for valid data set
     * @param {String} did The dataset id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2007}
     */
    this.validateData = function(did) {
      return this.validateDataWithHttpInfo(did)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Runs the unit test cases
     * Runs the unit test cases specified for Run
     * @param {String} rid The run id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2007} and HTTP response
     */
    this.validateRunWithHttpInfo = function(rid) {
      var postBody = null;

      // verify the required parameter 'rid' is set
      if (rid === undefined || rid === null) {
        throw new Error("Missing the required parameter 'rid' when calling validateRun");
      }


      var pathParams = {
        'rid': rid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2007;

      return this.apiClient.callApi(
        '/run/{rid}/test/validate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Runs the unit test cases
     * Runs the unit test cases specified for Run
     * @param {String} rid The run id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2007}
     */
    this.validateRun = function(rid) {
      return this.validateRunWithHttpInfo(rid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
