/**
 * AlgorithmHub
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body4', 'model/InlineResponse2003', 'model/InlineResponse2004'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Body4'), require('../model/InlineResponse2003'), require('../model/InlineResponse2004'));
  } else {
    // Browser globals (root is window)
    if (!root.algorithmhub) {
      root.algorithmhub = {};
    }
    root.algorithmhub.WorkspaceApi = factory(root.algorithmhub.ApiClient, root.algorithmhub.Body4, root.algorithmhub.InlineResponse2003, root.algorithmhub.InlineResponse2004);
  }
}(this, function(ApiClient, Body4, InlineResponse2003, InlineResponse2004) {
  'use strict';

  /**
   * Workspace service.
   * @module api/WorkspaceApi
   * @version 0.2.3
   */

  /**
   * Constructs a new WorkspaceApi. 
   * @alias module:api/WorkspaceApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Clone the workspace
     * Clone the given workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.cloneWorkspaceWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling cloneWorkspace");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/workspace/{wsid}/clone', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Clone the workspace
     * Clone the given workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.cloneWorkspace = function(wsid) {
      return this.cloneWorkspaceWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Creates new workspace
     * Creates a new workspace
     * @param {module:model/Body4} body The workspace type
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.createWorkspaceWithHttpInfo = function(body) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createWorkspace");
      }


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/workspace', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Creates new workspace
     * Creates a new workspace
     * @param {module:model/Body4} body The workspace type
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.createWorkspace = function(body) {
      return this.createWorkspaceWithHttpInfo(body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete an existing workspace
     * Delete an existing workspace
     * @param {String} wsid The workspace id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.deleteWorkspaceWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling deleteWorkspace");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/workspace/{wsid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete an existing workspace
     * Delete an existing workspace
     * @param {String} wsid The workspace id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.deleteWorkspace = function(wsid) {
      return this.deleteWorkspaceWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets workspace metadata
     * Gets workspace metadata
     * @param {String} wsid The workspace id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/InlineResponse2003} and HTTP response
     */
    this.detailWorkspaceWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling detailWorkspace");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/workspace/{wsid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Gets workspace metadata
     * Gets workspace metadata
     * @param {String} wsid The workspace id
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/InlineResponse2003}
     */
    this.detailWorkspace = function(wsid) {
      return this.detailWorkspaceWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get models associated
     * Get models associated with an exsisting workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/InlineResponse2004>} and HTTP response
     */
    this.listServicesWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling listServices");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = [InlineResponse2004];

      return this.apiClient.callApi(
        '/workspace/{wsid}/model', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get models associated
     * Get models associated with an exsisting workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/InlineResponse2004>}
     */
    this.listServices = function(wsid) {
      return this.listServicesWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get models associated
     * Get models associated with an exsisting workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/InlineResponse2004>} and HTTP response
     */
    this.listServices_0WithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling listServices_0");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = [InlineResponse2004];

      return this.apiClient.callApi(
        '/workspace/{wsid}/service', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get models associated
     * Get models associated with an exsisting workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/InlineResponse2004>}
     */
    this.listServices_0 = function(wsid) {
      return this.listServices_0WithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Returns list of workspaces
     * Returns a list of workspaces
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/InlineResponse2003>} and HTTP response
     */
    this.listWorkspacesWithHttpInfo = function() {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = [InlineResponse2003];

      return this.apiClient.callApi(
        '/workspace', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Returns list of workspaces
     * Returns a list of workspaces
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/InlineResponse2003>}
     */
    this.listWorkspaces = function() {
      return this.listWorkspacesWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Publish workspace to repo
     * Publish current workspace to repo
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.publishWorkspaceWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling publishWorkspace");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/workspace/{wsid}/publish', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Publish workspace to repo
     * Publish current workspace to repo
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.publishWorkspace = function(wsid) {
      return this.publishWorkspaceWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Share workspace with another user
     * Share workspace with another user
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.shareWorkspaceWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling shareWorkspace");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/workspace/{wsid}/share', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Share workspace with another user
     * Share workspace with another user
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.shareWorkspace = function(wsid) {
      return this.shareWorkspaceWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Turn off the workspace
     * Turn off the workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.turnOffWorkspaceWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling turnOffWorkspace");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/workspace/{wsid}/off', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Turn off the workspace
     * Turn off the workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.turnOffWorkspace = function(wsid) {
      return this.turnOffWorkspaceWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Turn on the workspace
     * Turn on the workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link 'String'} and HTTP response
     */
    this.turnOnWorkspaceWithHttpInfo = function(wsid) {
      var postBody = null;

      // verify the required parameter 'wsid' is set
      if (wsid === undefined || wsid === null) {
        throw new Error("Missing the required parameter 'wsid' when calling turnOnWorkspace");
      }


      var pathParams = {
        'wsid': wsid
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = [];
      var returnType = 'String';

      return this.apiClient.callApi(
        '/workspace/{wsid}/on', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Turn on the workspace
     * Turn on the workspace
     * @param {String} wsid The workspace base type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link 'String'}
     */
    this.turnOnWorkspace = function(wsid) {
      return this.turnOnWorkspaceWithHttpInfo(wsid)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
