/**
 * AlgorithmHub
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.algorithmhub);
  }
}(this, function(expect, algorithmhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new algorithmhub.InlineResponse20011();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20011', function() {
    it('should create an instance of InlineResponse20011', function() {
      // uncomment below and update the code to test InlineResponse20011
      //var instane = new algorithmhub.InlineResponse20011();
      //expect(instance).to.be.a(algorithmhub.InlineResponse20011);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new algorithmhub.InlineResponse20011();
      //expect(instance).to.be();
    });

    it('should have the property sid (base name: "sid")', function() {
      // uncomment below and update the code to test the property sid
      //var instane = new algorithmhub.InlineResponse20011();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instane = new algorithmhub.InlineResponse20011();
      //expect(instance).to.be();
    });

    it('should have the property runCount (base name: "runCount")', function() {
      // uncomment below and update the code to test the property runCount
      //var instane = new algorithmhub.InlineResponse20011();
      //expect(instance).to.be();
    });

    it('should have the property isPublic (base name: "isPublic")', function() {
      // uncomment below and update the code to test the property isPublic
      //var instane = new algorithmhub.InlineResponse20011();
      //expect(instance).to.be();
    });

    it('should have the property timeCreated (base name: "timeCreated")', function() {
      // uncomment below and update the code to test the property timeCreated
      //var instane = new algorithmhub.InlineResponse20011();
      //expect(instance).to.be();
    });

  });

}));
