/**
 * AlgorithmHub
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.algorithmhub);
  }
}(this, function(expect, algorithmhub) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new algorithmhub.InlineResponse2009();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2009', function() {
    it('should create an instance of InlineResponse2009', function() {
      // uncomment below and update the code to test InlineResponse2009
      //var instane = new algorithmhub.InlineResponse2009();
      //expect(instance).to.be.a(algorithmhub.InlineResponse2009);
    });

    it('should have the property lastModified (base name: "last-modified")', function() {
      // uncomment below and update the code to test the property lastModified
      //var instane = new algorithmhub.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property contentType (base name: "content-type")', function() {
      // uncomment below and update the code to test the property contentType
      //var instane = new algorithmhub.InlineResponse2009();
      //expect(instance).to.be();
    });

    it('should have the property cacheControl (base name: "cache-control")', function() {
      // uncomment below and update the code to test the property cacheControl
      //var instane = new algorithmhub.InlineResponse2009();
      //expect(instance).to.be();
    });

  });

}));
